server:
  port: 8280

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: work-shift-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

